FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y python3 python3-pip

COPY app /app/
WORKDIR /app
RUN pip3 install -r requirements.txt

EXPOSE 5000
 
ENV FLASK_APP=hello.py
ENV FLASK_ENV=development
CMD ["flask", "run", "--host", "0.0.0.0"]
 