---
version: "3.8"
#secrets example

services: 
    registry:
        image: registry:latest
        ports: 
            - "5000:5000"
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role==manager
        environment: 
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
        volumes:
            - "registry:/mnt/registry"

    flask:
        #get from local registry if not published
        image: "localhost:5000/flask"
        deploy: 
            mode: "replicated"
            replicas: 2
        secrets:
            - image_gallery_password
        configs:
            - source: flask_config
                target: /etc/flask.config
                mode: 0444
        ports:
            - "8888:5000"
        depends_on: 
            - "registry"

    db:
        image: "postgres"
        environment: 
            POSTGRES_PASSWORD: "v^l!o|EjMH?LM6.JkbV3`86(.D^4?)8w"
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        deploy:
            replicas: 1
        configs:
            - source: flask_config
                target: /etc/flask.config
                mode: 0444
        volumes:
            - "/Users/zacharylong/Dropbox/Zac Auburn Files/CPSC 4973 Cloud Computing/M6/M6Project/image-gallery-postgres:/var/lib/postgresql/data"

volumes:
    registry:
    image-gallery-postgres:
        driver: rexray/efs

secrets:
    image_gallery_password:
        external: true

configs:
    flask_config:
        file: flask.config