FROM ubuntu:latest
#RUN apt-get install -y apt-transport-https
RUN apt-get update -y && apt-get install -y python3 python3-pip libpcre3 libpcre3-dev

COPY app /app/
WORKDIR /app
RUN pip3 install -r requirements.txt
RUN useradd -m zac

EXPOSE 5555
EXPOSE 9191

USER zac

ENV FLASK_APP=hello.py
ENV FLASK_ENV=development
CMD ["uwsgi", "--http", ":5555", "--module", "hello:app", "--master", "--processes", "4", "--threads", "2", "--stats", "0.0.0.0:9191"]
