---
version: "3.8"

services: 
    # registry:
    #     image: registry:latest
    #     ports: 
    #         - "5000:5000"
    #     deploy:
    #         replicas: 1
    #         placement:
    #             constraints:
    #                 - node.role==manager
    #     environment: 
    #         REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
    #     volumes:
    #         - "registry:/mnt/registry"

    database:
        image: "postgres"
        environment: 
            POSTGRES_PASSWORD: "v^l!o|EjMH?LM6.JkbV3`86(.D^4?)8w"
            POSTGRES_USER: image_gallery
            POSTGRES_DB: image_gallery
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PORT: 5432
            
        deploy:
            replicas: 1
            placement:
                constraints:
                    - database==yes
        secrets:
            - ig_password
        configs:
            - source: flask_config
                target: /etc/flask.config
                mode: 0444
        volumes:
            - "/mnt/efs/postgres-data:/var/lib/postgresql/data"

    image_gallery:
        #get from local registry if not published
        #image: "image_gallery:latest"
        image: zacharylong/m6-cloud-computing:latest
        environment: 
            S3_IMAGE_BUCKET: zacs-m6-image-gallery
            COGNITO_SECRET: qrf18amslqvs04erroch6586fsncn63pqmqdovt1vk7huggqnep
            POSTGRES_HOST: "database"
        deploy: 
            mode: "replicated"
            replicas: 2
        secrets:
            - ig_password
            - flask_session_key
        configs:
            - source: flask_config
                target: /etc/flask.config
                mode: 0444
        ports:
            - "8888:5000"
        depends_on: 
            - "registry"
            - "database"

volumes:
    registry:
    data:
        driver: rexray/efs

secrets:
    image_gallery_password:
        external: true
    ig_password:
        external: true
    flask_session_key:
        external: true

configs:
    flask_config:
        file: flask.config