---
version: "3.8"

services: 

    database:
        image: "postgres"
        environment: 
            POSTGRES_PASSWORD: "v^l!o|EjMH?LM6.JkbV3`86(.D^4?)8w"
            POSTGRES_USER: image_gallery
            POSTGRES_DB: image_gallery
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_PORT: 5432
            
        deploy:
            replicas: 1
            placement:
                constraints:
                    - database==yes
        secrets:
            - ig_passwd
        configs:
            - source: flask_config
              target: /etc/flask.config
              mode: 0444
        volumes:
            - "/home/ec2-user/m6-docker-aws/init:/docker-entrypoint-initdb.d"
            - "/mnt/efs/postgres-data:/var/lib/postgresql/data"

    image_gallery:
        image: zacharylong/m6-cloud-computing:latest
        environment: 
            S3_IMAGE_BUCKET: zacs-m6-image-gallery
            COGNITO_SECRET: qrf18amslqvs04erroch6586fsncn63pqmqdovt1vk7huggqnep
            POSTGRES_HOST: "database"
        deploy: 
            mode: "replicated"
            replicas: 2
        secrets:
            - ig_passwd
            - flask_session_key
        configs:
            - source: flask_config
              target: /etc/flask.config
              mode: 0444
        ports:
            - "8888:5000"
        depends_on: 
            - "database"

volumes:
    registry:
    data:
        driver: rexray/efs

secrets:
    image_gallery_password:
        external: true
    ig_passwd:
        external: true
    flask_session_key:
        external: true

configs:
    flask_config:
        file: flask.config