---
version: "3"

services: 
    registry:
        image: registry:latest
        ports: 
            - "5000:5000"
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role==manager
        environment: 
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
        volumes: 
            - "registry:/mnt/registry"
            
    # pinger:
    #     image: alpine:latest
    #     # demo below running net
    #     # image: localhost:5000/net
    #     command: ["ping", "google.com"]
    #     deploy:
    #         mode: global
    #     depends_on: 
    #         - "registry"

    flask:
        #get from local registry if not published
        image: "localhost:5000/flask"
        deploy: 
            mode: "replicated"
            replicas: 2
            # placement:
            #     - node.labels.flask_server==yes
        depends_on: 
            - "registry"

    db:
        image: "postgres"
        environment: 
            POSTGRES_PASSWORD: "v^l!o|EjMH?LM6.JkbV3`86(.D^4?)8w"
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        deploy:
            mode: "replicated"
            replicas: 1
            placement:
                constraints:
                    - node.labels.postgres_server==yes
        volumes:
            - "/home/ec2-user/m6-docker-aws/image-gallery-postgres:/var/lib/postgresql/data"

volumes:
    registry:
